/**
 * Real-browser verification for the scarlettplayer.com pages.
 *
 * Companion to scripts/verify-browser.mjs, which covers playback. This one
 * covers the site around the player: every route renders without horizontal
 * overflow from a 320px phone to a 1440px desktop, in every scenario the demo
 * can be deep-linked to, every asset a page references is served from the
 * tree that gets deployed, every in-site link lands, and the sitemap names
 * exactly the pages that exist.
 *
 * Routes, on a local repo-root server at :8899:
 *
 *   /docs/                    the authored homepage (docs/index.html)
 *   /docs/demo/               the generated demo, which production serves at /demo/
 *   /demo/                    the source demo, the route verify-browser.mjs drives
 *   /docs/documentation/      the documentation index
 *   /docs/architecture/       docs/architecture.md
 *   /docs/plugin-authoring/   docs/plugin-authoring.md
 *   /docs/embed/              docs/embed-implementation.md
 *   /docs/contributing/       docs/contributing.md
 *   /docs/vs-videojs/         docs/scarlett-vs-videojs.md
 *   /docs/vs-mux/             docs/scarlett-vs-mux.md
 *   /docs/vs-bitmovin/        docs/scarlett-vs-bitmovin.md
 *
 * The last eight are the HTML documentation, generated by demo/docs-build.mjs
 * (run from build.cjs) and served on production at /<slug>/. They carry no
 * player and fetch no media.
 *
 * Checks, per route:
 *
 *   1. The page answers 200 and links the ONE stylesheet at the path its
 *      route expects. The homepage and both demo routes link it as a sibling,
 *      `<route>site.css`, and demo/build.cjs mirrors site.css and assets/
 *      beside each generated demo page. A `../site.css` from /demo/index.html
 *      would resolve to /site.css and never be requested, so the source route
 *      would render unstyled (review finding, 2026-09-19); this is the check
 *      that makes that impossible. The documentation pages are the opposite
 *      case on purpose: they link `../site.css` and `../assets/`, which is
 *      docs/site.css both locally (/docs/architecture/ -> /docs/site.css) and
 *      on production (/architecture/ -> /site.css), and no mirror is copied
 *      beside them. Each route names its expected href, and the check
 *      compares the resolved path without the ?v= stamp.
 *   2. Zero document horizontal overflow at 320/375/390/414/768/1024/1440.
 *      On the demo routes that is asserted for every scenario hash (#hls
 *      #mp4 #audio #audio-mini #whep #custom #playground #clips), switched
 *      in-page the way the scenario nav and Back/Forward do, and again with
 *      each hash loaded directly at phone width.
 *   3. Player placement on the demo routes' default scenario: at 390x844 the
 *      player's top is <= 280px and the whole player is on screen; at
 *      1440x900 the whole player is on screen without scrolling. Both are
 *      acceptance criteria of the redesign.
 *   4. Every <link rel=stylesheet>, <link rel*=icon>, <link rel=preload>,
 *      <link rel=alternate>,
 *      <img src>/<img srcset>, <source srcset>, video poster,
 *      og:image/twitter:image, and CSS url()
 *      or @import target (from linked sheets, <style> blocks and style=""
 *      attributes), collected across every scenario and viewport, answers
 *      200 with a non-empty body from the local server. An asset on any
 *      other origin fails outright: only our own imagery ships, and this
 *      harness must not need the public internet. og:image is an absolute
 *      production URL by nature, so it is mapped through the production
 *      route map (scarlettplayer.com/demo/ is docs/demo/, everything else is
 *      docs/) rather than assumed to live under a local /docs/ prefix.
 *   5. No uncaught exception on any route while switching scenarios, and no
 *      HLS manifest, segment or demo bundle requested by the initial load of
 *      any page without a player (the homepage, which only fetches them on
 *      the first Play, and the documentation pages, which never do).
 *   6. Every <a href> in the final document that points at this site, as a
 *      relative href or as an absolute scarlettplayer.com URL (mapped the
 *      same way as og:image), answers 200 with redirects not followed. The
 *      documentation pages are generated from Markdown whose links were
 *      written for GitHub, so a guide-to-guide link rewritten to the wrong
 *      slug is exactly the kind of mistake that renders fine and 404s on
 *      click. Links to any other origin (GitHub, npm, the sample media
 *      hosts) are counted and skipped: this harness must not need the
 *      internet. mailto:, tel:, javascript:, data: and blob: are skipped.
 *      On the routes marked `anchors` (the documentation pages, whose "On
 *      this page" lists and cross-links carry heading slugs, and the
 *      homepage, whose #main and #start they link back to) every #fragment
 *      whose target is one of those routes must name an id, or an <a name>,
 *      in the target's served HTML. The demo routes are deliberately not
 *      marked: their hashes are scenario routes read by demo.ts, not ids.
 *      The source demo's links are resolved from /docs/demo/, where
 *      production serves the same HTML, because its `../` links are written
 *      for scarlettplayer.com/demo/ and climb out of docs/ locally.
 *
 * And once, for the site as a whole:
 *
 *   7. docs/sitemap.xml lists exactly the pages production serves: every
 *      route above except the source-only /demo/, no more and no fewer,
 *      with each <loc> answering 200 through the production route map and
 *      no <lastmod> anywhere (the site rule: no fabricated dates). A page
 *      added to the build without a sitemap entry, or an entry left behind
 *      for a page that was removed, fails here. The Markdown published for
 *      agents is deliberately NOT in the sitemap: each guide's index.md
 *      duplicates its HTML page, which is the one to index, and agents find
 *      the files through /llms.txt and each page's rel=alternate instead.
 *   8. Every agent file (AGENT_FILES: llms.txt, llms-full.txt and each
 *      guide's and comparison's index.md) answers 200 with a body. llms-full.txt is linked
 *      from nowhere a page can reach, so this is the only check that sees it.
 *
 * Usage:
 *   pnpm build && node demo/build.cjs
 *   python3 -m http.server 8899 --bind 127.0.0.1   # from repo root
 *   node scripts/verify-site.mjs
 *
 * Requires the `playwright` package with its bundled Chromium installed
 * (`npx playwright install --with-deps chromium`), exactly as
 * verify-browser.mjs does. No other dependency: assets are fetched with
 * Node's own fetch.
 *
 * Exits 1 on any failed check and 2 when it cannot run at all (no server on
 * :8899). It fails loudly rather than skipping: a route that does not
 * answer, a page that links no stylesheet, a player that never initialises,
 * a hash that cannot be measured, a page with no in-site link to follow, a
 * fragment check with no fragment to check or a sitemap with no <loc> is a
 * FAIL with the route, viewport and hash in its name, never an empty pass.
 *
 * Every request a page makes to an origin other than 127.0.0.1 is aborted,
 * as verify-browser.mjs does. The demo's sample streams are hosted, so the
 * player shows its network-error overlay under this harness; that is
 * expected and is not what these checks look at.
 */
import { Buffer } from 'node:buffer';
import { chromium } from 'playwright';

const ORIGIN = 'http://127.0.0.1:8899';

/** Production origin, for the route map in checks 4, 6 and 7. */
const PRODUCTION_ORIGIN = 'https://scarlettplayer.com';

/** Every scenario the demo can be deep-linked to, canonical forms and aliases. */
const DEMO_HASHES = ['#hls', '#mp4', '#audio', '#audio-mini', '#whep', '#custom', '#playground', '#clips'];

/**
 * The routes under test.
 *
 * `hashes` is what the route is driven through for the overflow checks; the
 * homepage and the documentation pages have no scenario routing, so they are
 * measured once per viewport as loaded. `player` marks the routes that must
 * initialise `window.player` and meet the placement criteria. `stylesheet`
 * is the href check 1 expects, resolved against the route. `anchors` marks
 * the routes whose #fragments are element ids, so check 6 verifies links
 * into them; the demo's hashes are scenario names, never ids, and must not
 * be held to that. `sourceOnly` marks the one route production does not
 * serve, so the sitemap check leaves it out, and `servedAs` names where
 * production serves the same HTML. Check 6 resolves that route's relative
 * links from there: its `../documentation/` is right on
 * scarlettplayer.com/demo/ but climbs out of docs/ locally, to a
 * /documentation/ that was never meant to exist in the repo root.
 */
const ROUTES = [
  { path: '/docs/', name: 'homepage', hashes: [''], player: false, stylesheet: 'site.css', anchors: true },
  { path: '/docs/demo/', name: 'generated demo', hashes: DEMO_HASHES, player: true, stylesheet: 'site.css' },
  { path: '/demo/', name: 'source demo', hashes: DEMO_HASHES, player: true, stylesheet: 'site.css', sourceOnly: true, servedAs: '/docs/demo/' },
  { path: '/docs/documentation/', name: 'documentation index', hashes: [''], player: false, stylesheet: '../site.css', anchors: true },
  { path: '/docs/architecture/', name: 'architecture guide', hashes: [''], player: false, stylesheet: '../site.css', anchors: true },
  { path: '/docs/plugin-authoring/', name: 'plugin authoring guide', hashes: [''], player: false, stylesheet: '../site.css', anchors: true },
  { path: '/docs/embed/', name: 'embed guide', hashes: [''], player: false, stylesheet: '../site.css', anchors: true },
  { path: '/docs/contributing/', name: 'contributing guide', hashes: [''], player: false, stylesheet: '../site.css', anchors: true },
  { path: '/docs/vs-videojs/', name: 'Video.js comparison', hashes: [''], player: false, stylesheet: '../site.css', anchors: true },
  { path: '/docs/vs-mux/', name: 'Mux Player comparison', hashes: [''], player: false, stylesheet: '../site.css', anchors: true },
  { path: '/docs/vs-bitmovin/', name: 'Bitmovin comparison', hashes: [''], player: false, stylesheet: '../site.css', anchors: true },
];

/** Widths the redesign must not overflow at, each with a plausible height. */
const VIEWPORTS = [
  { width: 320, height: 568 },
  { width: 375, height: 812 },
  { width: 390, height: 844 },
  { width: 414, height: 896 },
  { width: 768, height: 1024 },
  { width: 1024, height: 768 },
  { width: 1440, height: 900 },
];

/** The two viewports the player-placement criteria are written against. */
const PHONE = { width: 390, height: 844 };
const DESKTOP = { width: 1440, height: 900 };

/** Lowest the player's top edge may sit on a 390x844 phone, in CSS px. */
const MAX_PHONE_PLAYER_TOP = 280;

/** The player container every harness drives; the redesign preserves the id. */
const PLAYER_SELECTOR = '#player';

/** How long a hash switch gets to settle before the layout is measured. */
const SETTLE_MS = 300;

/**
 * How long a demo route gets to initialise window.player after load.
 *
 * Nothing here waits on the network (every off-box request is aborted), so
 * this only has to cover script parse and plugin init on a slow runner.
 */
const PLAYER_TIMEOUT_MS = 20000;

/**
 * Requests the initial load of a page without a player must never make: the
 * homepage defers all of this to the first Play, and the documentation pages
 * have no player at all.
 */
const PLAYERLESS_FORBIDDEN = /\.m3u8(\?|$)|\.ts(\?|$)|\.m4s(\?|$)|\.mp4(\?|$)|demo\.bundle\.js/;

/** Link schemes check 6 has nothing to fetch for. */
const UNFETCHABLE_LINK = /^(mailto|tel|javascript|data|blob):/i;

/**
 * The Markdown the docs build publishes for agents, as local paths. Not
 * routes (nothing here is rendered or measured) and not sitemap entries
 * (check 7 fails if one is listed); check 8 fetches each. Each guide page
 * also links its index.md as rel=alternate, which check 4 fetches too.
 */
const AGENT_FILES = [
  '/docs/llms.txt',
  '/docs/llms-full.txt',
  '/docs/architecture/index.md',
  '/docs/plugin-authoring/index.md',
  '/docs/embed/index.md',
  '/docs/contributing/index.md',
  '/docs/vs-videojs/index.md',
  '/docs/vs-mux/index.md',
  '/docs/vs-bitmovin/index.md',
];

/** Where the sitemap lives on the local server (docs/ is production's root). */
const SITEMAP_URL = `${ORIGIN}/docs/sitemap.xml`;

const CSS_URL_RE = /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)"'\s]+))\s*\)/g;
const CSS_IMPORT_RE = /@import\s+(?!url\()["']([^"']+)["']/g;

const results = [];
const record = (name, pass, detail) => {
  results.push({ name, pass, detail });
  console.log(`${pass ? 'PASS' : 'FAIL'}  ${name}${detail ? '  -- ' + detail : ''}`);
};

/**
 * Fetch one URL from the local server and describe the answer.
 *
 * Redirects are not followed: a 301 from `assets` to `assets/` is a page
 * referencing a directory, which is a mistake even when it happens to land.
 *
 * @param {string} url - Absolute URL on the local server
 * @returns {Promise<{status: number, length: number, type: string, text: string, error?: string}>}
 */
const fetchLocal = async (url) => {
  try {
    const res = await fetch(url, { redirect: 'manual' });
    const body = Buffer.from(await res.arrayBuffer());
    const type = res.headers.get('content-type') ?? '';
    return {
      status: res.status,
      length: body.length,
      type,
      text: /css|text|html|xml/.test(type) ? body.toString('utf8') : '',
    };
  } catch (error) {
    return {
      status: 0,
      length: 0,
      type: '',
      text: '',
      error: String(error?.cause?.message ?? error?.message ?? error),
    };
  }
};

/**
 * Every url() and @import target in a piece of CSS, resolved against `base`.
 *
 * @param {string} css - Stylesheet text, a <style> block or a style="" value
 * @param {string} base - URL the relative references resolve against
 * @returns {string[]} Absolute URLs, data:/blob:/fragment references dropped
 */
const cssReferences = (css, base) => {
  const refs = [];
  const push = (raw) => {
    const value = (raw ?? '').trim();
    if (!value || /^(data|blob|javascript):/.test(value) || value.startsWith('#')) {
      return;
    }
    try {
      refs.push(new URL(value, base).href);
    } catch {
      refs.push(value);
    }
  };
  for (const match of css.matchAll(CSS_URL_RE)) {
    push(match[1] ?? match[2] ?? match[3]);
  }
  for (const match of css.matchAll(CSS_IMPORT_RE)) {
    push(match[1]);
  }
  return refs;
};

/**
 * Map a production URL onto the local server, or return null when the URL
 * is on neither origin.
 *
 * Production serves docs/ at the root and docs/demo/ at /demo/. A page's
 * relative references never need this; it exists for og:image and friends,
 * which are absolute by nature.
 *
 * @param {string} url - Absolute URL
 * @returns {string|null} The equivalent local URL, or null
 */
const toLocal = (url) => {
  let parsed;
  try {
    parsed = new URL(url);
  } catch {
    return null;
  }
  if (parsed.origin === ORIGIN) {
    return parsed.href;
  }
  if (parsed.origin === PRODUCTION_ORIGIN) {
    // /demo/ and everything else both land under docs/; the distinction is
    // spelled out because the deployed /demo/ is the GENERATED docs/demo/.
    return `${ORIGIN}/docs${parsed.pathname}${parsed.search}`;
  }
  return null;
};

/**
 * Open a page confined to the local server that records uncaught exceptions.
 *
 * @param {import('playwright').Browser} browser - The shared browser
 * @param {{width: number, height: number}} viewport - Initial viewport
 * @returns {Promise<{page: import('playwright').Page, pageErrors: string[], requests: string[]}>}
 */
const openPage = async (browser, viewport) => {
  const page = await browser.newPage({ viewport });
  await page.route(/^https?:\/\//, (route) => {
    const { hostname } = new URL(route.request().url());
    return hostname === '127.0.0.1' || hostname === 'localhost'
      ? route.continue()
      : route.abort('failed');
  });
  const pageErrors = [];
  const requests = [];
  page.on('pageerror', (err) => pageErrors.push(String(err)));
  page.on('request', (req) => requests.push(req.url()));
  return { page, pageErrors, requests };
};

/**
 * Let a hash switch or a resize settle before the layout is read.
 *
 * @param {import('playwright').Page} page - Page to wait on
 * @returns {Promise<void>}
 */
const settle = async (page) => {
  await page.waitForTimeout(SETTLE_MS);
  await page.evaluate(
    () => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)))
  );
};

/**
 * Wait for the demo to hand over `window.player`.
 *
 * The container div's id shadows window.player until demo.ts finishes init
 * and assigns the real instance, so a function-typed `load` is the signal.
 *
 * @param {import('playwright').Page} page - A page that has loaded a demo route
 * @returns {Promise<boolean>} Whether it initialised within the timeout
 */
const waitForPlayer = async (page) => {
  try {
    await page.waitForFunction(
      () => window.player && typeof window.player.load === 'function',
      { timeout: PLAYER_TIMEOUT_MS }
    );
    return true;
  } catch {
    return false;
  }
};

/**
 * Switch scenario in-page, the way the scenario nav and Back/Forward do.
 *
 * @param {import('playwright').Page} page - Page on a demo route
 * @param {string} hash - Scenario hash; '' leaves the URL alone
 * @returns {Promise<void>}
 */
const goHash = async (page, hash) => {
  if (hash) {
    await page.evaluate((h) => {
      location.hash = h;
    }, hash);
  }
  await settle(page);
};

/**
 * Measure document overflow, naming the widest offenders when there is any.
 *
 * Compared against `clientWidth` rather than `innerWidth` on purpose: both
 * exclude a vertical scrollbar, so a `100vw` element that overflows by the
 * scrollbar's width in a real browser is reported here too.
 *
 * @param {import('playwright').Page} page - Page to measure
 * @returns {Promise<{width: number, limit: number, offenders: string[]}>}
 */
const measureOverflow = (page) =>
  page.evaluate(() => {
    const doc = document.documentElement;
    const limit = doc.clientWidth;
    const width = Math.max(doc.scrollWidth, document.body?.scrollWidth ?? 0);
    if (width <= limit) {
      return { width, limit, offenders: [] };
    }
    const describe = (el) => {
      const cls =
        typeof el.className === 'string' && el.className.trim()
          ? '.' + el.className.trim().split(/\s+/).slice(0, 3).join('.')
          : '';
      return `${el.tagName.toLowerCase()}${el.id ? '#' + el.id : ''}${cls}`;
    };
    const offenders = [...document.querySelectorAll('body *')]
      .map((el) => ({ el, rect: el.getBoundingClientRect() }))
      .filter(({ rect }) => rect.width > 0 && rect.right > limit + 0.5)
      .sort((a, b) => b.rect.right - a.rect.right)
      .slice(0, 6)
      .map(({ el, rect }) => `${describe(el)} right=${Math.round(rect.right)}`);
    return { width, limit, offenders };
  });

/**
 * Where the player container sits in the viewport.
 *
 * @param {import('playwright').Page} page - Page on a demo route
 * @returns {Promise<{found: boolean, top: number, bottom: number, height: number, viewportHeight: number}>}
 */
const playerRect = (page) =>
  page.evaluate((selector) => {
    const el = document.querySelector(selector);
    if (!el) {
      return { found: false, top: 0, bottom: 0, height: 0, viewportHeight: innerHeight };
    }
    const rect = el.getBoundingClientRect();
    return {
      found: true,
      top: Math.round(rect.top),
      bottom: Math.round(rect.bottom),
      height: Math.round(rect.height),
      viewportHeight: innerHeight,
    };
  }, PLAYER_SELECTOR);

/**
 * Every asset reference in the current document, resolved to absolute URLs.
 *
 * Attributes are read rather than resolved properties so that every srcset
 * candidate is collected, not just the one the current viewport picked.
 *
 * @param {import('playwright').Page} page - Page to read
 * @returns {Promise<Array<{url: string, what: string}>>}
 */
const collectAssets = (page) =>
  page.evaluate(() => {
    const found = new Map();
    const add = (raw, what) => {
      const value = (raw ?? '').trim();
      if (!value || /^(data|blob|javascript):/.test(value) || value.startsWith('#')) {
        return;
      }
      let abs = value;
      try {
        abs = new URL(value, document.baseURI).href;
      } catch {
        // Left as written so the fetch below reports it as unparseable.
      }
      if (!found.has(abs)) {
        found.set(abs, what);
      }
    };
    const srcsetUrls = (srcset) =>
      (srcset ?? '')
        .split(',')
        .map((candidate) => candidate.trim().split(/\s+/)[0])
        .filter(Boolean);
    const cssRefs = (css) => {
      const refs = [];
      const re = /url\(\s*(?:"([^"]*)"|'([^']*)'|([^)"'\s]+))\s*\)/g;
      for (const match of (css ?? '').matchAll(re)) {
        refs.push(match[1] ?? match[2] ?? match[3]);
      }
      return refs;
    };

    document
      .querySelectorAll('link[rel~="stylesheet"]')
      .forEach((el) => add(el.getAttribute('href'), '<link rel=stylesheet>'));
    document
      .querySelectorAll('link[rel*="icon"]')
      .forEach((el) => add(el.getAttribute('href'), `<link rel="${el.getAttribute('rel')}">`));
    // A preload names the same font the stylesheet does, in a second place
    // that can drift on its own: a wrong href here is a wasted request and a
    // console warning in production, never a visible failure.
    // The docs pages point agents at their Markdown twin; a wrong href there
    // fails silently for every reader that follows it.
    document
      .querySelectorAll('link[rel~="alternate"][href]')
      .forEach((el) => add(el.getAttribute('href'), `<link rel=alternate type=${el.getAttribute('type') ?? '?'}>`));
    document
      .querySelectorAll('link[rel~="preload"][href]')
      .forEach((el) => add(el.getAttribute('href'), `<link rel=preload as=${el.getAttribute('as') ?? '?'}>`));
    document.querySelectorAll('img').forEach((el) => {
      add(el.getAttribute('src'), '<img src>');
      srcsetUrls(el.getAttribute('srcset')).forEach((u) => add(u, '<img srcset>'));
    });
    document
      .querySelectorAll('source[srcset]')
      .forEach((el) => srcsetUrls(el.getAttribute('srcset')).forEach((u) => add(u, '<source srcset>')));
    document.querySelectorAll('video').forEach((el) => add(el.getAttribute('poster'), 'video poster'));
    document
      .querySelectorAll('meta[property="og:image"], meta[name="twitter:image"]')
      .forEach((el) => add(el.getAttribute('content'), `<meta ${el.getAttribute('property') ?? el.getAttribute('name')}>`));
    document
      .querySelectorAll('style')
      .forEach((el) => cssRefs(el.textContent).forEach((u) => add(u, '<style> url()')));
    document
      .querySelectorAll('[style]')
      .forEach((el) => cssRefs(el.getAttribute('style')).forEach((u) => add(u, 'style="" url()')));

    return [...found].map(([url, what]) => ({ url, what }));
  });

/**
 * Every distinct <a href> in the current document, resolved against `base`.
 *
 * The base is passed in rather than read from document.baseURI so that the
 * source demo's links resolve from where production serves that HTML (see
 * `servedAs` on ROUTES).
 *
 * @param {import('playwright').Page} page - Page to read
 * @param {string} base - URL relative hrefs resolve against
 * @returns {Promise<Array<{raw: string, url: string|null}>>} `url` is null
 *   when the href does not parse
 */
const collectLinks = async (page, base) => {
  const hrefs = await page.evaluate(() =>
    [...document.querySelectorAll('a[href]')].map((el) => el.getAttribute('href').trim())
  );
  const found = new Map();
  for (const raw of hrefs) {
    let url = null;
    try {
      url = new URL(raw, base).href;
    } catch {
      // Reported by check 6 as unparseable.
    }
    const key = url ?? raw;
    if (!found.has(key)) {
      found.set(key, { raw, url });
    }
  }
  return [...found.values()];
};

/**
 * The route a local URL lands on, ignoring query, fragment and index.html.
 *
 * @param {string} localUrl - Absolute URL on the local server
 * @returns {object|undefined} The ROUTES entry, when it is one of them
 */
const routeFor = (localUrl) => {
  const { pathname } = new URL(localUrl);
  const path = pathname.replace(/index\.html$/, '');
  return ROUTES.find((r) => r.path === path);
};

/**
 * Every fragment an HTML document can be scrolled to: each element id, and
 * each <a name>, which browsers still honour.
 *
 * Read from the served HTML, not the live DOM. The documentation pages are
 * static, and a link has to work for a reader whose scripts have not run.
 * Attributes are read from real start tags only: the guides quote HTML in
 * their code samples (`<div id="player">`), escaped as text, and an id in a
 * code sample is not something a link can scroll to.
 *
 * @param {string} html - Document source
 * @returns {Set<string>} Fragment targets, with &amp; and friends decoded
 */
const anchorTargets = (html) => {
  const decode = (v) =>
    v.replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
  const targets = new Set();
  const attr = /(?:^|\s)(id|name)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/gi;
  for (const [, tag, attrs] of html.matchAll(/<([a-zA-Z][\w-]*)([^>]*)>/g)) {
    for (const [, name, dq, sq, bare] of attrs.matchAll(attr)) {
      if (name.toLowerCase() === 'id' || tag.toLowerCase() === 'a') {
        targets.add(decode(dq ?? sq ?? bare));
      }
    }
  }
  return targets;
};

/**
 * Pages fetched by check 6, keyed by URL without its fragment, so a link
 * that twenty TOC entries and three other pages point at is fetched once.
 */
const linkFetches = new Map();
const fetchLinkTarget = (url) => {
  if (!linkFetches.has(url)) {
    linkFetches.set(url, fetchLocal(url));
  }
  return linkFetches.get(url);
};

// ============================================================ PREFLIGHT
// The server has to be there before anything is a real result. A refused
// connection is a setup problem, reported as one, not as 25 failed checks.
{
  const probe = await fetchLocal(`${ORIGIN}/`);
  if (probe.status === 0) {
    console.error(`Cannot reach ${ORIGIN}: ${probe.error}`);
    console.error('Serve the repository root first: python3 -m http.server 8899 --bind 127.0.0.1');
    process.exit(2);
  }
}

const browser = await chromium.launch({ headless: true });

/** Assets to fetch after every route has been driven: url -> {what, routes}. */
const assets = new Map();
const noteAsset = (route, { url, what }) => {
  const entry = assets.get(url) ?? { what, routes: new Set() };
  entry.routes.add(route.path);
  assets.set(url, entry);
};

try {
  for (const route of ROUTES) {
    const url = `${ORIGIN}${route.path}`;
    console.log(`\n--- ${route.name}: ${route.path} ---`);

    // ---- 1. The page answers, and links its stylesheet where its route expects.
    const head = await fetchLocal(url);
    record(`[${route.path}] page answers 200`, head.status === 200, `status ${head.status}${head.error ? ' ' + head.error : ''}`);
    if (head.status !== 200) {
      // Nothing below can be measured against a page that is not there, and
      // every check it would have produced is a failure, not a skip.
      record(`[${route.path}] overflow, placement, asset and link checks`, false, 'page not served');
      continue;
    }

    const { page, pageErrors, requests } = await openPage(browser, VIEWPORTS[0]);
    const firstHash = route.hashes[0];
    // 'load', not verify-browser's 'domcontentloaded': a layout read before
    // the stylesheet and the images have arrived measures an unstyled page.
    await page.goto(`${url}${firstHash}`, { waitUntil: 'load' });

    let playerReady = false;
    if (route.player) {
      playerReady = await waitForPlayer(page);
      record(`[${route.path}] window.player initialised`, playerReady, playerReady ? '' : `not within ${PLAYER_TIMEOUT_MS}ms`);
    } else {
      // The homepage must stay light: no stream, no segments, no demo bundle
      // until the viewer asks for the player. The documentation pages have no
      // player to ask for, so the same assertion holds for them outright.
      await settle(page);
      const forbidden = requests.filter((r) => PLAYERLESS_FORBIDDEN.test(r));
      record(
        `[${route.path}] initial load requests no HLS manifest, segment or demo bundle`,
        forbidden.length === 0,
        forbidden.slice(0, 5).join(', ')
      );
    }

    // Compared without the query: the build stamps a cache-busting ?v= onto
    // the href, and it is the path that has to resolve from the page.
    const stylesheets = (await collectAssets(page)).filter((a) => a.what === '<link rel=stylesheet>');
    const expected = new URL(route.stylesheet, url).href;
    record(
      `[${route.path}] links its stylesheet as ${route.stylesheet} (${new URL(expected).pathname})`,
      stylesheets.some((a) => a.url.split('?')[0] === expected),
      stylesheets.length ? stylesheets.map((a) => a.url).join(', ') : 'no <link rel=stylesheet> on the page'
    );

    // ---- 2. No horizontal overflow, every viewport x every scenario.
    for (const viewport of VIEWPORTS) {
      await page.setViewportSize(viewport);
      await settle(page);
      for (const hash of route.hashes) {
        await goHash(page, hash);
        const label = `[${route.path} ${viewport.width}px${hash ? ' ' + hash : ''}]`;
        const overflow = await measureOverflow(page);
        record(
          `${label} no horizontal overflow`,
          overflow.width <= overflow.limit,
          overflow.width <= overflow.limit
            ? ''
            : `scrollWidth ${overflow.width} > ${overflow.limit}: ${overflow.offenders.join('; ')}`
        );
        (await collectAssets(page)).forEach((a) => noteAsset(route, a));
      }
    }

    // ---- 3. Player placement on the default scenario.
    if (route.player) {
      await page.setViewportSize(PHONE);
      await goHash(page, DEMO_HASHES[0]);
      const phone = await playerRect(page);
      record(
        `[${route.path} ${PHONE.width}x${PHONE.height} ${DEMO_HASHES[0]}] player top <= ${MAX_PHONE_PLAYER_TOP}px and fully on screen`,
        phone.found && phone.height > 0 && phone.top >= 0 && phone.top <= MAX_PHONE_PLAYER_TOP && phone.bottom <= phone.viewportHeight,
        phone.found ? `top ${phone.top}, bottom ${phone.bottom}, height ${phone.height}` : `${PLAYER_SELECTOR} not found`
      );

      await page.setViewportSize(DESKTOP);
      await goHash(page, DEMO_HASHES[0]);
      const desktop = await playerRect(page);
      record(
        `[${route.path} ${DESKTOP.width}x${DESKTOP.height} ${DEMO_HASHES[0]}] whole player visible without scrolling`,
        desktop.found && desktop.height > 0 && desktop.top >= 0 && desktop.bottom <= desktop.viewportHeight,
        desktop.found ? `top ${desktop.top}, bottom ${desktop.bottom}, height ${desktop.height}` : `${PLAYER_SELECTOR} not found`
      );
    }

    // ---- 6. Every in-site link in the final document lands, and on the
    // anchors routes every #fragment into an anchors route names an id.
    // Failures are recorded one per link; passes are summarised per route,
    // or a documentation page with forty TOC entries would bury the rest of
    // the output.
    {
      const links = await collectLinks(page, `${ORIGIN}${route.servedAs ?? route.path}`);
      let fetched = 0;
      let offSite = 0;
      let fragments = 0;
      let linkFailures = 0;
      let fragmentFailures = 0;
      for (const { raw, url: href } of links) {
        if (UNFETCHABLE_LINK.test(raw)) {
          continue;
        }
        // Absolute scarlettplayer.com links go through the production route
        // map, so https://scarlettplayer.com/architecture/ is checked as
        // /docs/architecture/, the file that will be served there.
        if (!href) {
          linkFailures += 1;
          record(`[${route.path}] link ${raw}`, false, 'href does not parse as a URL');
          continue;
        }
        const local = toLocal(href);
        if (!local) {
          offSite += 1;
          continue;
        }

        const target = new URL(local);
        const fragment = target.hash.slice(1);
        target.hash = '';
        const res = await fetchLinkTarget(target.href);
        fetched += 1;
        if (res.status !== 200) {
          linkFailures += 1;
          record(
            `[${route.path}] link ${raw} answers 200`,
            false,
            `${target.pathname}${target.search}: status ${res.status}${res.error ? ' ' + res.error : ''}`
          );
          continue;
        }

        // Only the anchors routes hold their fragments to an id, and only
        // for targets that are anchors routes too: a link from the homepage
        // to demo/#audio names a scenario, and is right not to match an id.
        const targetRoute = routeFor(target.href);
        if (!route.anchors || !fragment || !targetRoute?.anchors) {
          continue;
        }
        let name = fragment;
        try {
          name = decodeURIComponent(fragment);
        } catch {
          // A malformed escape is compared as written, and fails below.
        }
        fragments += 1;
        if (!anchorTargets(res.text).has(name)) {
          fragmentFailures += 1;
          record(
            `[${route.path}] link ${raw} names an id on ${targetRoute.path}`,
            false,
            `no id="${name}" or <a name="${name}"> in ${target.pathname}`
          );
        }
      }

      // At least one in-site link on every route: each page links at least
      // its own nav, so zero means the collection itself is broken.
      record(
        `[${route.path}] every in-site link answers 200`,
        linkFailures === 0 && fetched > 0,
        `${fetched} in-site links followed, ${offSite} off-site skipped` +
          (fetched === 0 ? ', but no in-site link was found to follow' : '') +
          (linkFailures ? `, ${linkFailures} failed` : '')
      );
      // Every anchors route has at least one fragment into another: the
      // documentation pages' headers link ../#start and their TOCs link
      // their own headings, and the homepage links #main and #start.
      if (route.anchors) {
        record(
          `[${route.path}] every #fragment link names an id on its target page`,
          fragmentFailures === 0 && fragments > 0,
          `${fragments} fragments checked` +
            (fragments === 0 ? ', but no fragment link into an anchors route was found' : '') +
            (fragmentFailures ? `, ${fragmentFailures} failed` : '')
        );
      }
    }

    // ---- 5. Nothing threw while all of that happened.
    record(`[${route.path}] no uncaught exceptions`, pageErrors.length === 0, pageErrors.slice(0, 3).join(' | '));
    await page.close();

    // ---- 2b. Each scenario loaded directly, at phone width. A direct link
    // and a refresh go through the controller's initial render, which is
    // not the same path as an in-page switch. Not attempted when the route
    // could not initialise its player once: that is already a failure
    // above, and eight more timeouts would only delay the verdict.
    if (route.player && !playerReady) {
      record(`[${route.path}] direct-load checks for every scenario`, false, 'not run: window.player never initialised on this route');
    }
    if (route.player && playerReady) {
      for (const hash of route.hashes) {
        const direct = await openPage(browser, PHONE);
        await direct.page.goto(`${url}${hash}`, { waitUntil: 'load' });
        const ready = await waitForPlayer(direct.page);
        await settle(direct.page);
        const overflow = await measureOverflow(direct.page);
        record(
          `[${route.path} ${PHONE.width}px ${hash} direct load] player initialised and no horizontal overflow`,
          ready && overflow.width <= overflow.limit && direct.pageErrors.length === 0,
          [
            ready ? '' : 'player did not initialise',
            overflow.width <= overflow.limit ? '' : `scrollWidth ${overflow.width} > ${overflow.limit}: ${overflow.offenders.join('; ')}`,
            direct.pageErrors.length ? `uncaught: ${direct.pageErrors[0]}` : '',
          ].filter(Boolean).join('; ')
        );
        (await collectAssets(direct.page)).forEach((a) => noteAsset(route, a));
        await direct.page.close();
      }
    }
  }

  // ============================================================ ASSETS
  // 4. Everything any page referenced, fetched from the local server. Linked
  // stylesheets are read for their own url() and @import references, which
  // join the queue, so a background image three sheets deep is checked too.
  console.log('\n--- assets referenced by the pages ---');
  const queue = [...assets.entries()];
  const seen = new Set(queue.map(([url]) => url));
  while (queue.length) {
    const [url, { what, routes }] = queue.shift();
    const where = [...routes].join(' ');
    const local = toLocal(url);
    if (!local) {
      record(`${what} ${url} (${where})`, false, 'not served from the local tree - only our own assets may be referenced');
      continue;
    }

    const res = await fetchLocal(local);
    const ok = res.status === 200 && res.length > 0;
    record(
      `${what} ${url} (${where})`,
      ok,
      ok ? `${res.length} bytes` : `status ${res.status}${res.error ? ' ' + res.error : ''}${res.status === 200 ? ', empty body' : ''}`
    );

    if (ok && (what === '<link rel=stylesheet>' || /css/.test(res.type))) {
      for (const ref of cssReferences(res.text, local)) {
        if (!seen.has(ref)) {
          seen.add(ref);
          queue.push([ref, { what: `css url() in ${new URL(local).pathname}`, routes }]);
        }
      }
    }
  }
  record('at least one asset was referenced and checked', assets.size > 0, `${assets.size} distinct references`);
} finally {
  await browser.close();
}

// ============================================================ SITEMAP
// 7. The sitemap and the route table must describe the same site. Every
// <loc> is a production URL, mapped onto the local tree the same way og:image
// is, and the result compared as a set with the routes production serves.
// A missing entry is a page search engines are never told about; an extra
// one is a URL they are sent to that 404s.
{
  console.log('\n--- sitemap ---');
  const sitemap = await fetchLocal(SITEMAP_URL);
  record(
    'sitemap.xml answers 200',
    sitemap.status === 200 && sitemap.text.length > 0,
    `status ${sitemap.status}${sitemap.error ? ' ' + sitemap.error : ''}`
  );
  if (sitemap.status === 200) {
    const locs = [...sitemap.text.matchAll(/<loc>\s*([^<]*?)\s*<\/loc>/g)].map((m) => m[1]);
    record('sitemap.xml lists at least one <loc>', locs.length > 0, `${locs.length} entries`);

    const expected = new Set(ROUTES.filter((r) => !r.sourceOnly).map((r) => `${ORIGIN}${r.path}`));
    const agentFiles = new Set(AGENT_FILES.map((p) => `${ORIGIN}${p}`));
    const listed = new Map();
    for (const loc of locs) {
      // A <loc> has to be a production URL: a local or relative one would
      // map to something here and pass, then mean nothing to a crawler.
      let onProduction = false;
      try {
        onProduction = new URL(loc).origin === PRODUCTION_ORIGIN;
      } catch {
        // Unparseable; reported below.
      }
      if (!onProduction) {
        record(`sitemap <loc> ${loc} is a ${PRODUCTION_ORIGIN} URL`, false, 'not on the production origin');
        continue;
      }
      listed.set(toLocal(loc), loc);
    }

    const missing = [...expected].filter((u) => !listed.has(u)).map((u) => new URL(u).pathname);
    const extra = [...listed].filter(([u]) => !expected.has(u) && !agentFiles.has(u)).map(([, loc]) => loc);
    const agents = [...listed].filter(([u]) => agentFiles.has(u)).map(([, loc]) => loc);
    record(
      'sitemap.xml lists exactly the pages production serves',
      missing.length === 0 && extra.length === 0 && agents.length === 0,
      [
        missing.length ? `missing (local routes): ${missing.join(', ')}` : '',
        extra.length ? `not a served route: ${extra.join(', ')}` : '',
        agents.length ? `agent Markdown listed (duplicates an HTML page; agents use llms.txt): ${agents.join(', ')}` : '',
      ].filter(Boolean).join('; ') || `${listed.size} entries, one per route`
    );

    for (const [local, loc] of listed) {
      const res = await fetchLocal(local);
      record(
        `sitemap <loc> ${loc} answers 200`,
        res.status === 200,
        `${new URL(local).pathname}: status ${res.status}${res.error ? ' ' + res.error : ''}`
      );
    }

    const lastmods = (sitemap.text.match(/<lastmod\b/g) ?? []).length;
    record('sitemap.xml carries no <lastmod>', lastmods === 0, lastmods ? `${lastmods} found` : '');
  }
}

// ============================================================ AGENT FILES
// 8. The Markdown published for agents exists and has content.
{
  console.log('\n--- agent files ---');
  for (const file of AGENT_FILES) {
    const res = await fetchLocal(`${ORIGIN}${file}`);
    record(
      `agent file ${file} answers 200 with a body`,
      res.status === 200 && res.length > 0,
      `status ${res.status}, ${res.length} bytes${res.error ? ' ' + res.error : ''}`
    );
  }
}

// ============================================================ SUMMARY
const failed = results.filter((r) => !r.pass);
console.log(`\n==== ${results.length - failed.length}/${results.length} checks passed ====`);
if (failed.length) {
  console.log('FAILED:', failed.map((f) => f.name).join(' | '));
  process.exitCode = 1;
}
